name: Binky
main: com.zeiban.BinkyPlugin
author: Zeiban
version: 0.0.1
description: Backup and Restore Worlds using Git
commands:
   git-commit: 
      description: Commits current state of the world to the repository
      usage: /git-commit world comment
   git-log:
      description: Displays the commit log
      usage: /git-log
   git-reset:
      description: Reset the state of the world
      usage: /git-reset 